[package]
name = "espike"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "*"
clap = { version = "3.0", features = ["derive"] }
indicatif = "*"
rand = "*"
rust-htslib = "*"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
